- hosts: mywebservers

  tasks:
   - name: Nginx setup
     apt: pkg=nginx state=installed update_cache=true

   - name: Start Nginx
     service: name=nginx state=started

   - name: Open port 

   - name: index.html copy
     template: src=index.html.j2 dest=/usr/share/nginx/html/index.html
